- name: Deploy MERN stack app using Docker from Docker Hub
  hosts: web_servers
  become: yes
  tasks:
    - name: Update system packages (Amazon Linux 2)
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

    - name: Update system packages (Amazon Linux 2023)
      dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"

    # Install Docker
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Docker is Installed for Ansible User
      shell: usermod -aG docker {{ ansible_user }}

    # Pull Backend Image from Docker Hub
    - name: Pull Backend Docker image from Docker Hub
      command: docker pull safeer85/sams-backend:latest

    # Run Backend Container
    - name: Run Backend Docker container
      command: >
        docker run -d --name backend_container -p 5000:5000 safeer85/sams-backend:latest

    # Pull Frontend Image from Docker Hub
    - name: Pull Frontend Docker image from Docker Hub
      command: docker pull safeer85/sams-frontend:latest

    # Run Frontend Container
    - name: Run Frontend Docker container
      command: >
        docker run -d --name frontend_container -p 3000:3000 --env REACT_APP_API_URL=http://{{ ansible_default_ipv4.address }}:5000 safeer85/sams-frontend:latest

    # Install Nginx (for reverse proxy)
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Configure Nginx reverse proxy
      template:
        src: nginx_reverse_proxy.j2
        dest: /etc/nginx/conf.d/mern_stack.conf

    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted
        enabled: yes

