- name: Deploy MERN stack app (Client + Server)
  hosts: web_servers
  become: yes
  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Enable Amazon Linux Extras for Node.js
      command: amazon-linux-extras enable nodejs14

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install Git
      yum:
        name: git
        state: present

    # Clone the Client repository (React app)
    - name: Clone the React client repository
      git:
        repo: 'https://github.com/safeer85/student-attendance/client'  # Replace with your React repo URL
        dest: '/home/ec2-user/client'
        version: master  # Optional: specify a branch

    # Clone the Server repository (Node.js app)
    - name: Clone the Node.js server repository
      git:
        repo: 'https://github.com/safeer85/student-attendance/server'  # Replace with your Node.js repo URL
        dest: '/home/ec2-user/server'
        version: master  # Optional: specify a branch

    # Install npm (if not installed)
    - name: Install npm
      yum:
        name: npm
        state: present

    # Install dependencies for the React client
    - name: Install dependencies for React client
      command: npm install
      args:
        chdir: '/home/ec2-user/client'

    # Build the React client (production build)
    - name: Build the React client
      command: npm run build
      args:
        chdir: '/home/ec2-user/client'

    # Install dependencies for the Node.js server
    - name: Install dependencies for Node.js server
      command: npm install
      args:
        chdir: '/home/ec2-user/server'

    # Install PM2 globally
    - name: Install PM2 globally
      command: npm install -g pm2

    # Start the Node.js server using PM2
    - name: Start the Node.js server using PM2
      command:
        cmd: pm2 start index.js
        chdir: '/home/ec2-user/server'

    # Save PM2 process list
    - name: Save PM2 process list
      command: pm2 save

    # Install Nginx (optional)
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Configure Nginx reverse proxy
      template:
        src: nginx_reverse_proxy.j2
        dest: /etc/nginx/conf.d/mern_stack.conf

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    # Restart PM2 to ensure everything is running after Nginx setup
    - name: Restart PM2 processes
      command: pm2 restart all
